### ISSUE TITLE
Uncaught ReferenceError: geoError is not defined

### ISSUE THREAD

**Issue by lincolnanders5** [robbawebba/night-light#15]
Steps to reproduce:

Nothing's changed between when I installed it yesterday and today. I just left Atom open on my computer last night after finishing working and when I opened it up this afternoon the geoError error got thrown like every 5 seconds.

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [night-light](https://github.com/robbawebba/night-light) package 1.0.4

### Stack Trace

Uncaught ReferenceError: geoError is not defined

```
At /Users/lincolnanders/.atom/packages/night-light/lib/night-light.js:154

ReferenceError: geoError is not defined
    at Object.updateLocationAndCheckThemes (/packages/night-light/lib/night-light.js:154:11)
    at Object.tick (/packages/night-light/lib/night-light.js:219:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-html-preview 0.2.2 
autoclose-html 0.23.0 
hey-pane 1.0.0 
html-to-css 0.2.2 
night-light 1.0.4 
```

**Comment by robbawebba** [comment]
@lincolnanders Thanks for reporting this! I'll take a look at this later tonight. I'll try my best to reproduce this, but I have never seen this through my own use of the package so it might be difficult.  

If you happen to gather any more info about this bug while I investigate it, I would love to hear it! Thanks again for your help.

**Comment by user00101010** [comment]
I am experiencing the same issue. The steps to reproduce it is disabling the "Auto-update location". After a period of time (not sure what triggers it), it starts producing the error message every few seconds. The addon itself also stops working at all, albeit having manual coordinates entered.

Upon re-enabling the option the error messages stop instantly and the add-on starts working again. How does the auto-update location work by the way? How does it detect your location?

Also thank you very much for developing this great add-on! There seem to be a few similar options around but yours is the only one which I found working reliably (albeit this little quirk). I am truly grateful and the functionality is awesome! 

I actually switched to Atom solely for this purpose (since I was happy using gedit for my limited needs) and I'm more than satisfied. Really happy I switched actually, a lot of benefits to gedit and probably some boosted productivity. Awesome!

**Comment by robbawebba** [comment]
@user00101010 Thanks for reporting steps to reproduce! I'll try to reproduce right now and let you know what I find.

> How does the auto-update location work by the way? How does it detect your location?

The user's location is determined in the function `updateLocationAndCheckThemes()` in [night-light.js line 150](https://github.com/robbawebba/night-light/blob/develop/lib/night-light.js#L150). It relies on the [Navigator API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) that's built into most browsers (and electron is basically a browser :stuck_out_tongue_closed_eyes: ). It includes a function that gets the user's general location (zip code in the U.S., basically).

The electron project includes a Google API key by default that supports geolocation, but it's included in every distribution/installation of an Electron-based application so it often runs out of its API request quota. You can read more about it here: https://github.com/electron/electron/blob/master/docs/api/environment-variables.md#google_api_key

And thanks for the kind words! I really appreciate it and I'm glad you find it useful :) and welcome to Atom overall! It's definitely more feature-rich than gedit and very customizable. I haven't used Atom in awhile though. I've been doing a lot more embedded software development lately and vi / vim is usually available on any embedded Linux system.

**Comment by robbawebba** [comment]
@user00101010 Talking through the location function made me uncover the bug! It's in the same function, `updateLocationAndCheckThemes()`. geoError was undefined because I forgot to prefix the funciton call with `this`, so it couldn't find the function. I'll create a pull request for this change now :)
